#!/bin/sh

module="lcd_driver"
device="lcd"
mode="664"

# invoke insmod with all arguments we got
# and use a pathname, as newer modutils don't look in . by default
/sbin/insmod ./$module.ko $* || exit 1

# remove stale nodes
rm -f /dev/${device}

# major=$(awk "\\$2= =\"$module\" {print \\$1}" /proc/devices)
major=$(grep ${device} /proc/devices | cut -f1 -d' ' | head -n1)
mknod /dev/${device} c $major 0

# give appropriate group/permissions, and change the group.
# Not all distributions have staff, some have "wheel" instead.
#group="staff"
#grep -q '^staff:' /etc/group || group="wheel"
#chgrp $group /dev/${device}[0-3]
#chmod $mode /dev/${device}[0-3]

